language: python
sudo: false
python:
- '3.4'
services:
  - postgresql
addons:
  postgresql: '9.5'
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
env:
- DJANGO_SETTINGS_MODULE="service_info.settings.dev"
install:
- pip install -U pip
- pip install -r requirements/dev.txt
- npm install
- npm update
before_script:
- createdb -E UTF-8 service_info -U postgres -O $USER
- psql service_info -c "CREATE EXTENSION postgis;" -U postgres
- gulp build
script:
- coverage run manage.py test
- coverage report -m --fail-under 60
- flake8 .
- (cd docs; make html)
notifications:
  email:
  - servicemap-team@caktusgroup.com
  hipchat:
    rooms:
      secure: hzO52z0lmODDT8vulhP8HQt/9dFxXOtRq9g/+ejt65yeAyPQCNXjbU6h4vyR91klgFAhbGeUe77w0Cwra9IqwMmCo8TTeIL9WTct3NyspxoEGq2OJiyNvw3LoCyJdk1ZynzHF8Q0G2OowRHHpmp+5v/WlPhPcPUhZLn1/BJRZGno5878wHTAK3t2p1GNTQgdAyt92Y95H4eEmLsyAQF45jR8C0B6o2c3+WJKv9rrCQO8XL5KPCvLGD8mvV/swfD/GL4Yb6a7jtLmiJ2UYdMt46gR6q1yF7VlUzCR4juVLEoBb+OGfz0xuI+NA/5lThFhe98Xm73xNdEyncoo534B1Xk+DhT93COp3+avdB5ionf1E99saRWZ2TRUrh73SRnoe8shecZXwM2HA3fDdJQ1ioO2uk720TjCBLjbZ1SCdLjW0CjiPZjzSdep50SeKe+UrG/4Q3GVumG9p2yAkTUwNpC65a/UxxkB+IbIiF9ZswYfRyfU/WN4NnV28XsOVBOxRKrAZv86q9fSGqttrV09YSkpl3AcUDhOxtM5jAa5KVbBBj9aQ5/74GW6kE+v84nriCLUyNHJwB6q0XeGwHvTktVURubyGECsJZ91eY/otrpV793g+kQsAn5trxB5hXNfah9Q/8l7GGMa17aG3wdmR+0fc6oZvsnMLwo1Lhaly2A=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
